//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQLChiTieu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCHITEUEntities : DbContext
    {
        public QLCHITEUEntities()
            : base("name=QLCHITEUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBOChiTieu> DBOChiTieux { get; set; }
        public virtual DbSet<LOAICHITIEU> LOAICHITIEUx { get; set; }
        public virtual DbSet<LOAITHUNHAP> LOAITHUNHAPs { get; set; }
    }
}
