//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQLChiTieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAICHITIEU
    {
        public int maLoaiCT { get; set; }
        public Nullable<int> iCon { get; set; }
        public string tenLoaiTN { get; set; }
    }
}
